[package]
name = "xmas_carol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordinal = "0.3.2"
ansi_term = "0.12.1"
